apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kaasc-webserver-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kaasc-webserver
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
