apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaasc-webserver
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kaasc-webserver
  template:
    metadata:
      labels:
        app: kaasc-webserver
    spec:
      containers:
      - name: kaasc-webserver-container
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
